name: jenkins

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 5000:5000
    container_name: jenkins
    volumes:
     # - /home/root/jenkins/compose/configuration:var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
