name: pgadmin4

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin4
    ports:
      - 8080:8080
    environment:
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_DEFAULT_PASSWORD=
      - PGADMIN_DEFAULT_EMAIL=
