name: keycloak

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    restart: always
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KC_HOSTNAME: localhost
      - KC_HOSTNAME_PORT: 8080
      - KC_HOSTNAME_STRICT_BACKCHANNEL: false
      - KC_HTTP_ENABLED: true
      - KC_HOSTNAME_STRICT_HTTPS: false
      - KC_HEALTH_ENABLED: true
      - KC_METRICS_ENABLED: true
      #- KEYCLOAK_ADMIN: admin
      - KC_BOOTSTRAP_ADMIN_USERNAME: admin
      #- KEYCLOAK_ADMIN_PASSWORD: change_me
      - KC_BOOTSTRAP_ADMIN_PASSWORD: change_me
      - KC_DB: postgres
      - KC_DB_URL: jdbc:postgresql://url/db
      - KC_DB_USERNAME: postgre
      - KC_DB_PASSWORD: change_me
    volumes:
      - keycloak:/opt/keycloak/data/